version: "2.1"
services:
  base:
    build: .
    working_dir: /opt/app
    volumes:
      - .:/opt/app
  frontend:
    extends: base
    ports:
      - "8080:8080"
    command: bash -c "npm install && node_modules/.bin/webpack-dev-server --host 0.0.0.0"
  backend:
    extends: base
    command: bash -c "npm install && npm run start:docker"
    volumes:
      - ./.env:/opt/app/.env
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:3.4
    volumes: 
      - /data/db:/data/db
