version: "3"
services:
  frontend:
    image: happy-mate
    ports:
      - "8080:8080"
    command: "node_modules/.bin/webpack-dev-server --host 0.0.0.0"
  backend:
    image: happy-mate
    command: "npm run start:docker"
    volumes:
      - ./.env:/opt/app/.env
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:3.4
